### ISSUE TITLE
Recommendation: Simplify CSS

### ISSUE THREAD

**Issue by melissamcewen** [magdarogowska/prj-rev-bwfs-dasmoto#4]
If you have a style that several things share it's best to make one style for it and then give that class to each. If you need an individual override, give the item an ID and then target that
here are some helpful articles about this
http://vanseodesign.com/css/dry-principles/
https://css-tricks.com/the-difference-between-id-and-class/

```css
.item h2 {
  font-size: 32px;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```

```html
    <h2 id="brush">Brushes</h2>

```
